// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_clubs
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-09-11, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `LAPTOP-LUDK4GVJ`, CPU: `11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_clubs
// --extrinsic=*
// --execution=wasm
// --steps
// 50
// --repeat
// 20
// --output
// pallets/clubs/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_clubs.
pub trait WeightInfo {
	fn add_club(s: u32, ) -> Weight;
	fn add_member(s: u32, ) -> Weight;
}

/// Weights for pallet_clubs using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Clubs Clubs (r:1 w:1)
	/// The range of component `s` is `[0, 100]`.
	fn add_club(s: u32, ) -> Weight {
		Weight::from_be(14_909_000 as u64)
			// Standard Error: 2_000
			.saturating_add(Weight::from_be(4_000 as u64).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: Clubs Clubs (r:1 w:0)
	// Storage: Clubs Members (r:1 w:1)
	/// The range of component `s` is `[0, 100]`.
	fn add_member(s: u32, ) -> Weight {
		Weight::from_be(15_146_000 as u64)
			// Standard Error: 1_000
			.saturating_add(Weight::from_be(35_000 as u64).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Clubs Clubs (r:1 w:1)
	/// The range of component `s` is `[0, 100]`.
	fn add_club(s: u32, ) -> Weight {
		Weight::from_be(14_909_000 as u64)
			// Standard Error: 2_000
			.saturating_add(Weight::from_be(4_000 as u64).saturating_mul(s as u64))
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: Clubs Clubs (r:1 w:0)
	// Storage: Clubs Members (r:1 w:1)
	/// The range of component `s` is `[0, 100]`.
	fn add_member(s: u32, ) -> Weight {
		Weight::from_be(15_146_000 as u64)
			// Standard Error: 1_000
			.saturating_add(Weight::from_be(35_000 as u64).saturating_mul(s as u64))
			.saturating_add(RocksDbWeight::get().reads(2 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
}